# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sample_models}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Hwang"]
  s.date = %q{2010-11-06}
  s.description = %q{
A library for making it extremely fast for Rails developers to set up and save ActiveRecord instances when writing test cases. It aims to:

* meet all your validations automatically
* only make you specify the attributes you care about
* give you a rich set of features so you can specify associated values as concisely as possible
* do this with as little configuration as possible
}
  s.email = %q{francis.hwang@profitably.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/sample_models.rb",
     "lib/sample_models/creation.rb",
     "lib/sample_models/finder.rb",
     "lib/sample_models/model.rb",
     "lib/sample_models/sampler.rb",
     "sample_models.gemspec",
     "spec/sample_models_spec.rb",
     "spec_or_test/database.yml",
     "spec_or_test/setup.rb",
     "spec_or_test/specs_or_test_cases.rb",
     "spec_or_test/vendor/validates_email_format_of/CHANGELOG",
     "spec_or_test/vendor/validates_email_format_of/MIT-LICENSE",
     "spec_or_test/vendor/validates_email_format_of/README",
     "spec_or_test/vendor/validates_email_format_of/TODO",
     "spec_or_test/vendor/validates_email_format_of/init.rb",
     "spec_or_test/vendor/validates_email_format_of/lib/validates_email_format_of.rb",
     "spec_or_test/vendor/validates_email_format_of/rakefile",
     "spec_or_test/vendor/validates_email_format_of/test/database.yml",
     "spec_or_test/vendor/validates_email_format_of/test/fixtures/people.yml",
     "spec_or_test/vendor/validates_email_format_of/test/fixtures/person.rb",
     "spec_or_test/vendor/validates_email_format_of/test/schema.rb",
     "spec_or_test/vendor/validates_email_format_of/test/test_helper.rb",
     "spec_or_test/vendor/validates_email_format_of/test/validates_email_format_of_test.rb",
     "tasks/sample_models_tasks.rake",
     "test/test_sample_models.rb",
     "uninstall.rb",
     "vendor/ar_query/MIT-LICENSE",
     "vendor/ar_query/README",
     "vendor/ar_query/ar_query.gemspec",
     "vendor/ar_query/init.rb",
     "vendor/ar_query/install.rb",
     "vendor/ar_query/lib/ar_query.rb",
     "vendor/ar_query/spec/ar_query_spec.rb",
     "vendor/ar_query/tasks/ar_query_tasks.rake",
     "vendor/ar_query/uninstall.rb"
  ]
  s.homepage = %q{http://github.com/fhwang/sample_models}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A library for making it extremely fast for Rails developers to set up and save ActiveRecord instances when writing test cases}
  s.test_files = [
    "spec/sample_models_spec.rb",
     "test/test_sample_models.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

