# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sample_models"
  s.version = "2.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Hwang"]
  s.date = "2012-03-02"
  s.description = "\nA library for making it extremely fast for Rails developers to set up and save ActiveRecord instances when writing test cases. It aims to:\n\n* meet all your validations automatically\n* only make you specify the attributes you care about\n* give you a rich set of features so you can specify associated values as concisely as possible\n* do this with as little configuration as possible\n"
  s.email = "francis.hwang@profitably.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/sample_models.rb",
    "lib/sample_models/attribute_sequence.rb",
    "lib/sample_models/creation.rb",
    "lib/sample_models/initializer.rb",
    "lib/sample_models/model.rb",
    "lib/sample_models/sampler.rb",
    "log/.gitkeep",
    "sample_models.gemspec",
    "tasks/sample_models_tasks.rake",
    "test/db/placeholder",
    "test/setup/models.rb",
    "test/setup/schema.rb",
    "test/test_helper.rb",
    "test/unit/belongs_to_test.rb",
    "test/unit/configuration_test.rb",
    "test/unit/has_many_through_test.rb",
    "test/unit/named_sample_test.rb",
    "test/unit/polymorphic_belongs_to_test.rb",
    "test/unit/sample_test.rb",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/fhwang/sample_models"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "A library for making it extremely fast for Rails developers to set up and save ActiveRecord instances when writing test cases"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
  end
end

